### ISSUE TITLE
Add TypeScript typings

### ISSUE THREAD

**Issue by jurijtokarski** [dzek69/react-source-of-truth#4]
Add internal (in package source) or external (as part of `@types`) TypeScript typings for the package.

**Comment by jurijtokarski** [comment]
@dzek69 can you please assign me for this? :)

**Comment by dzek69** [comment]
I'd go for internal typings of course.

**Comment by jurijtokarski** [comment]
I will prepare it in a few days if you allow me to.

**Comment by dzek69** [comment]
Sure, thank you!
